[project]
name = "pop-up-brief"
version = "1.1.1"
description = "Displays reminders as pop-up windows at specific times"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "configparser>=7.2.0",
    "datetime>=5.5",
]
